### ISSUE TITLE
Doublon apparu des deux listes déroulantes sur la page de démarrage

### ISSUE THREAD

**Issue by djulien19** [Valeureux/community-web#12]
![uploads/f396d1d5-c41a-468b-8c6a-b3f4a6112b97/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff396d1d5-c41a-468b-8c6a-b3f4a6112b97%2Fblob)

**Comment by welsh-dwarf** [comment]
Julien, je n'arrive pas à reproduire le bug. Est ce qu'on pourrait discuter de comment le reproduire? 

![selection_003](https://cloud.githubusercontent.com/assets/695866/9149849/eaac892a-3dbd-11e5-8263-5f9aaa93d7d7.png)
