### ISSUE TITLE
Langue par défaut

### ISSUE THREAD

**Issue by djulien19** [Valeureux/community-web#58]

**Comment by djulien19** [comment]
Au chargement du site, la langue par défaut est celle du template user. Nous ne retrouvons pas cela pour une personne non connectée, test réalisé en vidant les caches.

![uploads/d29e5527-80f0-4c68-a914-d957ef0394c0/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd29e5527-80f0-4c68-a914-d957ef0394c0%2Fblob)

**Comment by welsh-dwarf** [comment]
La langue par default dans Odoo est celle définit dans configuration -> website -> settings:

![selection_002](https://cloud.githubusercontent.com/assets/695866/9149784/2a04cbea-3dba-11e5-8b32-2b15f83ab471.png)

**Comment by djulien19** [comment]
Désolé... Paramétrage de base mais je pensais que nous l'avions fait évolué !
