### ISSUE TITLE
traduction erreur mdp ressaisie

### ISSUE THREAD

**Issue by djulien19** [Valeureux/community-web#59]

**Comment by djulien19** [comment]
Les mots de passent ne correspondent pas, veuillez les resaisir. 
-> 2 fautes d'orthographe importantes !
-> Merci de changer la traduction au texte demandé : Merci de taper les mêmes mots de passe !

**Comment by welsh-dwarf** [comment]
Corrigé

**Comment by djulien19** [comment]
Merci !
