### ISSUE TITLE
Libellé code postal

### ISSUE THREAD

**Issue by djulien19** [Valeureux/community-web#6]

**Comment by djulien19** [comment]
![uploads/1d4cf6f4-6d2e-45fa-9373-3d8426ceeabc/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1d4cf6f4-6d2e-45fa-9373-3d8426ceeabc%2Fblob)

**Comment by djulien19** [comment]
à traduire

**Comment by welsh-dwarf** [comment]
La traduction est déjà faite dans le code.
![selection_004](https://cloud.githubusercontent.com/assets/695866/9149856/14c91ade-3dbe-11e5-99ac-792a61ce84c4.png)

**Comment by djulien19** [comment]
ok !
