### ISSUE TITLE
SMS tickbox

### ISSUE THREAD

**Issue by djulien19** [Valeureux/community-web#62]

**Comment by djulien19** [comment]
Je ne visualise pas dans la fiche contact la coche SMS receive notification, et j'aimerai pouvoir faire un appel vers celle-ci et bien sûr pouvoir l'alimenter en mass.

**Comment by welsh-dwarf** [comment]
Ce champ est visible lors de la modification de l'utilisateur (cf specs), est ce qu'il faudrai le déplacer dans partenaire?

**Comment by djulien19** [comment]
Je n'ai pas réussi à le retrouver dans la fiche utilisateur non plus, oui il le faudrait dans partenaire onglet achats-ventes

**Comment by welsh-dwarf** [comment]
Bon, je viens de l'ajouter dans partenaire view.
