### ISSUE TITLE
différents modes d'affichage MKP

### ISSUE THREAD

**Issue by djulien19** [Valeureux/community-web#66]
quand je clique sur un autre format, celui-ci reste et il est impossible de revenir à un autre. 
De plus seul esl modes : 4 vignettes et 2 vignettes fonctionnent et pas la grille.

![image](https://cloud.githubusercontent.com/assets/6325713/9644159/51587aae-518b-11e5-95ed-a18a39ee773e.png)

**Comment by welsh-dwarf** [comment]
Julien, 

Pour moi ça fonctionne, ensuite, il y a pas mal de differences entre https://github.com/atout-serenite/community-web@master et https://github.com/Valeureux/community-web.git@master, donc le souci pourrai venir de là.

A+

David

**Comment by florent-valeureux** [comment]
Aujourd'hui les repo utilisés viennent de https://github.com/atout-serenite/community-web@master et non plus de community-web. En outre attention nous allons basculer vers: https://github.com/Valeureux/wezer-marketplace
